
apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n
  template:
    metadata:
      labels:
        app: n8n
    spec:
      containers:
        - name: n8n
          image: docker.n8n.io/n8nio/n8n:latest
          ports:
            - containerPort: 5678
          env:
            - name: DB_TYPE
              value: postgresdb
            - name: DB_POSTGRESDB_DATABASE
              value: n8n
            - name: DB_POSTGRESDB_HOST
              value: n8n-db-cnpg-v1-rw.cnpg-dev.svc.cluster.local
            - name: DB_POSTGRESDB_PORT
              value: "5432"
            - name: DB_POSTGRESDB_USER
              valueFrom:
                secretKeyRef:
                  name: n8n-db-secret
                  key: username
            - name: DB_POSTGRESDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: n8n-db-secret
                  key: password
            - name: DB_POSTGRESDB_SCHEMA
              value: public
            - name: GENERIC_TIMEZONE
              value: Europe/Stockholm
            - name: TZ
              value: Europe/Stockholm
            - name: N8N_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: n8n-encryption
                  key: key
            - name: N8N_PORT
              value: "5678"
              # Disable Telemetry (Diagnostics + Usage Tracking)
            - name: N8N_DEFAULT_EDITION
              value: "community"
            - name: N8N_RUNNERS_MODE
              value: internal
            - name: N8N_LOG_LEVEL
              value: debug
            - name: N8N_DIAGNOSTICS_ENABLED
              value: "false"
            - name: N8N_DISABLE_PRODUCTION_MAIN_MENU
              value: "true"
            - name: N8N_VERSION_NOTIFICATIONS_ENABLED
              value: "false"
            - name: N8N_HIRING_BANNER_ENABLED
              value: "false"
            - name: N8N_TEMPLATES_ENABLED
              value: "false"
            - name: N8N_PERSONALIZATION_ENABLED
              value: "false"
            - name: N8N_COMMUNITY_NODES_ENABLED
              value: "false"
          volumeMounts:
            - name: n8n-data
              mountPath: /home/node/.n8n
      volumes:
        - name: n8n-data
          persistentVolumeClaim:
            claimName: n8n-data

